// Code generated by protoc-gen-go.
// source: proto/fdtask.proto
// DO NOT EDIT!

/*
Package datamodel is a generated protocol buffer package.

It is generated from these files:
	proto/fdtask.proto

It has these top-level messages:
	FileDeliverTask
	MessageAck
*/
package datamodel

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type FileDeliverTask struct {
	TaskName         *string  `protobuf:"bytes,1,req,name=TaskName" json:"TaskName,omitempty"`
	Target           []string `protobuf:"bytes,2,rep,name=Target" json:"Target,omitempty"`
	ImageDescJson    []byte   `protobuf:"bytes,3,req,name=ImageDescJson" json:"ImageDescJson,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *FileDeliverTask) Reset()                    { *m = FileDeliverTask{} }
func (m *FileDeliverTask) String() string            { return proto.CompactTextString(m) }
func (*FileDeliverTask) ProtoMessage()               {}
func (*FileDeliverTask) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FileDeliverTask) GetTaskName() string {
	if m != nil && m.TaskName != nil {
		return *m.TaskName
	}
	return ""
}

func (m *FileDeliverTask) GetTarget() []string {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *FileDeliverTask) GetImageDescJson() []byte {
	if m != nil {
		return m.ImageDescJson
	}
	return nil
}

type MessageAck struct {
	IsSuccess        *bool   `protobuf:"varint,1,req,name=IsSuccess" json:"IsSuccess,omitempty"`
	ErrMsg           *string `protobuf:"bytes,2,opt,name=ErrMsg" json:"ErrMsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MessageAck) Reset()                    { *m = MessageAck{} }
func (m *MessageAck) String() string            { return proto.CompactTextString(m) }
func (*MessageAck) ProtoMessage()               {}
func (*MessageAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MessageAck) GetIsSuccess() bool {
	if m != nil && m.IsSuccess != nil {
		return *m.IsSuccess
	}
	return false
}

func (m *MessageAck) GetErrMsg() string {
	if m != nil && m.ErrMsg != nil {
		return *m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*FileDeliverTask)(nil), "datamodel.FileDeliverTask")
	proto.RegisterType((*MessageAck)(nil), "datamodel.MessageAck")
}

var fileDescriptor0 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4b, 0x29, 0x49, 0x2c, 0xce, 0xd6, 0x03, 0x73, 0x84, 0x38, 0x53, 0x12, 0x4b,
	0x12, 0x73, 0xf3, 0x53, 0x52, 0x73, 0x94, 0xbc, 0xb8, 0xf8, 0xdd, 0x32, 0x73, 0x52, 0x5d, 0x52,
	0x73, 0x32, 0xcb, 0x52, 0x8b, 0x42, 0x80, 0x6a, 0x84, 0x04, 0xb8, 0x38, 0x40, 0xb4, 0x5f, 0x62,
	0x6e, 0xaa, 0x04, 0xa3, 0x02, 0x93, 0x06, 0xa7, 0x10, 0x1f, 0x17, 0x5b, 0x48, 0x62, 0x51, 0x7a,
	0x6a, 0x89, 0x04, 0x93, 0x02, 0x33, 0x90, 0x2f, 0xca, 0xc5, 0xeb, 0x99, 0x9b, 0x98, 0x0e, 0xd4,
	0x55, 0x9c, 0xec, 0x55, 0x9c, 0x9f, 0x27, 0xc1, 0x0c, 0x54, 0xc6, 0xa3, 0xa4, 0xcf, 0xc5, 0xe5,
	0x9b, 0x5a, 0x5c, 0x0c, 0x94, 0x70, 0x4c, 0xce, 0x16, 0x12, 0xe4, 0xe2, 0xf4, 0x2c, 0x0e, 0x2e,
	0x4d, 0x4e, 0x06, 0x0a, 0x81, 0xcd, 0xe1, 0x00, 0x99, 0xe3, 0x5a, 0x54, 0xe4, 0x5b, 0x9c, 0x0e,
	0x34, 0x87, 0x51, 0x83, 0x13, 0x10, 0x00, 0x00, 0xff, 0xff, 0x7e, 0x34, 0x79, 0xa6, 0x9c, 0x00,
	0x00, 0x00,
}
