// Code generated by protoc-gen-go.
// source: models.proto
// DO NOT EDIT!

package datamodel

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type FileDeliverTask struct {
	TaskName         *string  `protobuf:"bytes,1,req,name=TaskName" json:"TaskName,omitempty"`
	Target           []string `protobuf:"bytes,2,rep,name=Target" json:"Target,omitempty"`
	ImageDescJson    []byte   `protobuf:"bytes,3,req,name=ImageDescJson" json:"ImageDescJson,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *FileDeliverTask) Reset()                    { *m = FileDeliverTask{} }
func (m *FileDeliverTask) String() string            { return proto.CompactTextString(m) }
func (*FileDeliverTask) ProtoMessage()               {}
func (*FileDeliverTask) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *FileDeliverTask) GetTaskName() string {
	if m != nil && m.TaskName != nil {
		return *m.TaskName
	}
	return ""
}

func (m *FileDeliverTask) GetTarget() []string {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *FileDeliverTask) GetImageDescJson() []byte {
	if m != nil {
		return m.ImageDescJson
	}
	return nil
}

type MessageAck struct {
	IsSuccess        *bool   `protobuf:"varint,1,req,name=IsSuccess" json:"IsSuccess,omitempty"`
	ErrMsg           *string `protobuf:"bytes,2,opt,name=ErrMsg" json:"ErrMsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MessageAck) Reset()                    { *m = MessageAck{} }
func (m *MessageAck) String() string            { return proto.CompactTextString(m) }
func (*MessageAck) ProtoMessage()               {}
func (*MessageAck) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *MessageAck) GetIsSuccess() bool {
	if m != nil && m.IsSuccess != nil {
		return *m.IsSuccess
	}
	return false
}

func (m *MessageAck) GetErrMsg() string {
	if m != nil && m.ErrMsg != nil {
		return *m.ErrMsg
	}
	return ""
}

type KeepAlive struct {
	NodeType         *uint32 `protobuf:"varint,1,req,name=NodeType" json:"NodeType,omitempty"`
	NodeId           *string `protobuf:"bytes,2,req,name=NodeId" json:"NodeId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *KeepAlive) Reset()                    { *m = KeepAlive{} }
func (m *KeepAlive) String() string            { return proto.CompactTextString(m) }
func (*KeepAlive) ProtoMessage()               {}
func (*KeepAlive) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *KeepAlive) GetNodeType() uint32 {
	if m != nil && m.NodeType != nil {
		return *m.NodeType
	}
	return 0
}

func (m *KeepAlive) GetNodeId() string {
	if m != nil && m.NodeId != nil {
		return *m.NodeId
	}
	return ""
}

type StartSendFile struct {
	TaskName         *string `protobuf:"bytes,1,req,name=TaskName" json:"TaskName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StartSendFile) Reset()                    { *m = StartSendFile{} }
func (m *StartSendFile) String() string            { return proto.CompactTextString(m) }
func (*StartSendFile) ProtoMessage()               {}
func (*StartSendFile) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *StartSendFile) GetTaskName() string {
	if m != nil && m.TaskName != nil {
		return *m.TaskName
	}
	return ""
}

func init() {
	proto.RegisterType((*FileDeliverTask)(nil), "datamodel.FileDeliverTask")
	proto.RegisterType((*MessageAck)(nil), "datamodel.MessageAck")
	proto.RegisterType((*KeepAlive)(nil), "datamodel.KeepAlive")
	proto.RegisterType((*StartSendFile)(nil), "datamodel.StartSendFile")
}

var fileDescriptor1 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x8e, 0xcb, 0x6a, 0x86, 0x30,
	0x10, 0x85, 0xf9, 0x7f, 0xa1, 0x98, 0x41, 0x7b, 0x09, 0x14, 0x5c, 0xda, 0xac, 0xdc, 0xb4, 0x7d,
	0x06, 0xa1, 0x2d, 0x68, 0xd1, 0x8d, 0xbe, 0x40, 0x48, 0x06, 0x11, 0x2f, 0x91, 0x4c, 0x5a, 0xe8,
	0xdb, 0x77, 0x62, 0x97, 0x5d, 0x0d, 0x73, 0xe6, 0xcc, 0x39, 0x1f, 0x64, 0x9b, 0xb3, 0xb8, 0xd2,
	0xcb, 0xe1, 0x5d, 0x70, 0x52, 0x58, 0x1d, 0xf4, 0xa9, 0xa8, 0x16, 0xee, 0x3e, 0xe6, 0x15, 0xdf,
	0x70, 0x9d, 0xbf, 0xd1, 0x8f, 0x9a, 0x16, 0x79, 0x0f, 0x69, 0x9c, 0xbd, 0xde, 0xb0, 0xb8, 0x94,
	0xd7, 0x4a, 0xc8, 0x5b, 0xb8, 0x19, 0xb5, 0x9f, 0x30, 0x14, 0xd7, 0x32, 0xe1, 0xfd, 0x11, 0xf2,
	0x66, 0xd3, 0x13, 0x7f, 0x91, 0x69, 0xc9, 0xed, 0x45, 0xc2, 0xb6, 0x4c, 0xbd, 0x02, 0x74, 0x48,
	0xc4, 0x87, 0xda, 0x2c, 0xf2, 0x01, 0x44, 0x43, 0xc3, 0x97, 0x31, 0x2c, 0x9d, 0x39, 0x69, 0xcc,
	0x79, 0xf7, 0xbe, 0xa3, 0x89, 0x73, 0x2e, 0x95, 0x50, 0xcf, 0x20, 0x3e, 0x11, 0x8f, 0x3a, 0x76,
	0xc7, 0xda, 0x9e, 0x91, 0xc6, 0x9f, 0xe3, 0xaf, 0x36, 0x8f, 0xf6, 0xa8, 0x34, 0x96, 0xed, 0x8c,
	0xa1, 0x9e, 0x20, 0x1f, 0x82, 0xf6, 0x61, 0xc0, 0xdd, 0x46, 0xe8, 0xff, 0xa4, 0xbf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x34, 0xb5, 0xf8, 0x26, 0xe8, 0x00, 0x00, 0x00,
}
